### ISSUE TITLE
Support for async/await in command handlers

### ISSUE THREAD

**Issue by stiano** [JasperFx/oakton#16]
With ability to support cancellation token.

E.g. OaktonAsyncCommand:
`public abstract Task<bool> ExecuteAsync(T input, CancellationToken cancellationToken);`

**Comment by RTodorov** [comment]
Hi guys,

Any chance this will be addressed in the near future?

Thanks

**Comment by gregbair** [comment]
Does this implement it? Is this in the latest Nuget package?

https://github.com/JasperFx/oakton/blob/master/src/Oakton/OaktonAsyncCommand.cs

**Comment by jeremydmiller** [comment]
@gregbair It's just waiting on me to look over it a little bit more and kick out a Nuget. Sometime this week.

**Comment by jeremydmiller** [comment]
Publishing the Nuget now as 1.4.0.
