### ISSUE TITLE
Accept RegisterCommand(typeof(T))

### ISSUE THREAD

**Issue by joaofx** [JasperFx/oakton#26]
Hi!

First of all, super cool library. Thanks for sharing it.

Currently, it seems there is two ways to register commands on CommandFactory::

```
RegisterCommand<T>()
RegisterCommands(Assembly assembly)
```

I need register by Type not using generics.

`RegisterCommand(typeof(T))`

Would you accept a pull request for that?

Thanks again.

**Comment by jeremydmiller** [comment]
@joaofx Hey, sorry I missed this. I would accept a PR, but I'm in the code this week and I can do that pretty quickly.

**Comment by joaofx** [comment]
Uhhh that's awesome! Thanks a million!!
