### ISSUE TITLE
Usage with optional arguments broken

### ISSUE THREAD

**Issue by chadly** [JasperFx/oakton#34]
Trying out the library. Copy pasted the [_Getting Started_ example](https://jasperfx.github.io/oakton/documentation/getting_started/). The usage with optional arguments does not work.

When running:

```
dotnet run -- "Alex Smith"
```

it always shows the **Invalid Usage** until you specify the color as well:

```
dotnet run -- "Alex Smith" Green
```

**Comment by chadly** [comment]
Tried with `v2.0.1`, `v2.0.0` - broken.

It works as expected in `v.1.5.0`.

**Comment by aidanjryan** [comment]
2.0.1 should have included a recent fix for this, i'll take a look using the getting started example

**Comment by jeremydmiller** [comment]
I'm on this one in the next day or two

**Comment by jeremydmiller** [comment]
I think the fix PR just got missed in the last release. Next Nuget will have the fix. I've verified the behavior in master.
