### ISSUE TITLE
Should not parse flags from IEnumerable<string>

### ISSUE THREAD

**Issue by dzarda** [JasperFx/oakton#38]
I'm trying to forward args to a BenchmarkDotNet method:

`BenchmarkSwitcher.Run(string[] args, ...)`

BenchmarkDotNet expects war `Main(string[] args)` args and is run in the following manner:

```
dotnet run -c Release -- --job short --runtimes clr core --filter *BenchmarkClass1*
```

My input class looks as follows:
```cs
public class BenchInput : RickInput
{
    [Description("BenchmarkDotNet Run args")]
    public IEnumerable<string> Args { get; set; }
}
```

Is there a way to use Oakton to propagate string args[] "verbatim" ?

**Comment by jeremydmiller** [comment]
Not as an argument, but you can as a flag: https://jasperfx.github.io/oakton/documentation/flags/enumerable/

I'm very sorry about how long it's taken to respond here:(
