### ISSUE TITLE
[FlagAlias] can it be used for arguments?

### ISSUE THREAD

**Issue by nvrnight** [JasperFx/oakton#39]
The documentation shows an example of where [FlagAlias] is used on a property called "c", which is an argument, not a flag. When I use [FlagAlias] on my arguments, it doesn't work. Since it doesn't work, I have no way of making a required named parameter. I'd certainly like to be explicit about names on all my parameters while having a way to mark them required, because a lot of parameters can make the command unruly and unreadable.

**Comment by tjrobinson** [comment]
@nvrnight Not really, as far as I can tell. Though this may be an option for you: https://gitter.im/JasperFx/oakton?at=5b6a821f3bca002dcbd8e8b6

**Comment by jeremydmiller** [comment]
@nvrnight Flags are assumed to be optional in Oakton. Not exactly what you're looking for maybe.
