### ISSUE TITLE
Merge Oakton.AspNetCore into Oakton

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/oakton#47]
Combine the two projections

**Comment by jeremydmiller** [comment]
Long since done.

**Comment by bbrandt** [comment]
Hi @jeremydmiller, 
If someone new is finding out about `Oakton.AspNetCore` from a blog article and lands at https://www.nuget.org/packages/Oakton.AspNetCore/ it is difficult to discover that it has been merged into the Oakton project.  
![image](https://github.com/JasperFx/oakton/assets/602767/532c1eed-a55b-4ace-aebc-519222794298)

Is there a way we can redirect people to the Oakton project so potential users of the AspNetCore feature set may not be discouraged by what looks like an abandoned package?  

I found this but I've never done it before:
https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

If there's anything I can do to help with this, let me know.  Thanks!
