### ISSUE TITLE
Usage of opts file

### ISSUE THREAD

**Issue by lvermeulen** [JasperFx/oakton#50]
I cannot figure out usage of the .opts file.

I have commands that have flags. When I make an .opts file that contains some of these flags, Oakton tells me:
`Invalid usage
Unknown argument or flag for value `

When I include the command in the .opts file, Oakton tells me the same thing. How should I use the .opts file?

Incidentally, I *love* this library! :-)

**Comment by lvermeulen** [comment]
A sample command would be:

`	[Description("Bla.", Name = "list-dependencies")]
	public class ListDependenciesCommand : OaktonAsyncCommand<ListDependenciesCommandInput>
	{
		public ListDependenciesCommand()
		{
			Usage("Bla.")
				.ValidFlags(
					x => x.OrganizationFlag,
					x => x.ProjectNameFlag
				);
		}

		public override async Task<bool> Execute(ListDependenciesCommandInput input)
		{
			return true;
		}
	}
`

**Comment by jeremydmiller** [comment]
@lvermeulen I'm **very** sorry for how long this took. The opts file thingie has to be applied at the application level itself. I did push through some code just now for the 4.0 release that enables the opts file thing for apps bootstrapped by `HostBuilder` or `WebApplication` now.
