### ISSUE TITLE
.NET 6?

### ISSUE THREAD

**Issue by larsholm** [JasperFx/oakton#54]
How do I get this to work in .NET 6?

**Comment by jeremydmiller** [comment]
Gimme until early next week to get Oakton 4.0 up:)

**Comment by jeremydmiller** [comment]
https://jeremydmiller.com/2021/11/29/jasperfx-oss-plans-for-v6-marten-et-al/

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/oakton/commit/fa223143510693d10bf01a5d3734191b10c95546
