### ISSUE TITLE
Provide the capability to allow stateful resources to have dependencies

### ISSUE THREAD

**Issue by SeanFarrow** [JasperFx/oakton#81]
I really like the stateful resource feature, but what would be really nice is to have the ability to allow one stateful resource to only run after another had successfully executed.

For example, let's say I'm using asp.net Identity to manage a user database with EntityFramework. I would want ot run migrations, then potentially seed some users.

**Comment by jeremydmiller** [comment]
Oh, yeah, I'll buy into that one.
